# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build:
    desc: Build the Go binary
    cmds:
      - go build ./cmd/lectures-notifier

  run:
    desc: Load .env and run the binary
    cmds:
      - set -a; source .env; set +a; ./lectures-notifier

  default:
    desc: Build the Go project
    cmds:
      - task: build

  k8s:create-secret:
    desc: Create or update lectures-notifier-secrets from .env
    cmds:
      - ./scripts/k8s-create-secret.sh

  k8s:docker-desktop-smoke:
    desc: Apply CronJobs to docker-desktop, patch to 1m, run one job, tail logs
    cmds:
      - ./scripts/k8s-docker-desktop-smoke.sh
