version: '3'

includes:
  scraper:
    taskfile: ./scraper/Taskfile.yml
    dir: ./scraper

tasks:
  docker:up:
    desc: Start local scraper stack services with Docker Compose
    cmds:
      - docker compose -f docker-compose.yml up -d

  docker:down:
    desc: Stop local compose services
    cmds:
      - docker compose -f docker-compose.yml down
